project:
  type: book

book:
  title: "인공지능 시대의 윤리 또는 윤리적 인공지능 - 기술, 정책, 철학"
  author: "김상호, 박대민, 박선희, 박찬경, 사영준, 유용민, 이정현, 이창준, 이혜온"
  date: today
  chapters:
    - index.qmd
    #- intro.qmd
    - part: first.qmd
      chapters: 
        - basic.qmd
        - info.qmd
        - post.qmd
    - part: second.qmd
      chapters:
        - tai.qmd
        - ineq.qmd
        - labor.qmd
        - copy.qmd
        - psych.qmd
        
    - part: third.qmd
      chapters:
        - fml.qmd
        - xai.qmd
    - references.qmd

bibliography: ethics.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



