---
title: "cut"
editor: visual
---




=


그 이유는 너무나도 학제적이기 때문이다. 너무나도 많은 발달이 있었다. 포스트휴먼 이야기는 사이버네틱스가 얽혀오기도 하고, 산업은 경제학이 얽혀온다. 

이 때문에, 해외에서도 아주 잘 짜여진 교과서를 보기는 어려운 것이 현실이다. 

어떻게 할지, EU는 어떻게 할지...학자들은 뭐라고 할지, 선고를 기다리는 사람들처럼 바라보고 있고, 윤리가 우리의 삶에 너무도 가까이 있다느 것을 알면서도, 보고서에서만 만납니다.
기업은 이 문제를 회피할 수 없을 것이며, 사실상 인공지능에 모든 것을 맡길 미래에 인간이 할 것은 윤리적 판단일 뿐이라는 이야기를 합니다.  시

1부는, 2부는... 


에 대한 이해를 

살아가는 산업과 노동, 가치 등, 삶에 대한 이해를 완전히 바꾸어버릴 것이라는 것을 의미한다. 
하지만 어쩐지, 

소문으로 떠돌던 OpenAI의 서비스는 그 때부터 우리의 대화 주제를 완전히 바꾸어버렸습니다. 바이러스를 대체하고 말았지요 (이것의 철학적 의미란...). 아직 우리의 삶을 모조리 바꾸었는지는 모르겠지만, 우리의 언어와 사고방식은 분명 바뀌었습니다. 학생들은 번역기를 이용한 티가 팍팍 나는 레포트를 써 내고 있습니다. 또 그 이전에도 있었던 추천 알고리즘을 인공지능이라고 부르기 시작했습니다. 어찌 보면, 이미 우리 주변에 와 있던 인공지능을 이제야 알아보고 화들짝 놀란 것 같기도 합니다.   





문제는 그보다도 근본적인 것으로 보입니다. 우리의 삶을 떠나, 인공지능의 삶에 대한 이야기까지 이루어지고 있습니다.

우리는 이러한 변화에 대해 얼마나 준비하고 있을까요?
사실 인공지능이 모든 것을 해 준다면, 우리에게 필요한 것은 인공지능을 설계하고 조작하는 능력 만큼이나, 인공지능과 어떻게 함께 살아가야 할 것인가에 대한 준비가 아닐까요. 

이 책은 그러한 관점에서 윤리에 대해 이야기 하고자 합니다. 윤리는 함께 살아가는 것에 대한 이야기 입니다.




정책 보고서들과 해외의 뉴스들이 오가고 있다. 

급변하는,,,Open AI 

뉴욕 타임즈 v. Open AI
미국의 헐리우드 파업에서 AI의 역할...

그런데, EU의 것들만 봐도, 어마어마한 정치적 논란 속에서... 그리고 서류들이 오가고 있는 상황 속에서....

https://www.europarl.europa.eu/doceo/document/TA-9-2023-0236_EN.html

Demystifying the Draft EU Artificial Intelligence Act
Analysing the good, the bad, and the unclear elements of the proposed approach


또, ACM Fair ML 등에서는 철학자들과 공학자들 간의 철학적 논의가 오가고 있다. 


우리의 이야기는 너무도 피상적, 기술적.
-> 우리 교육에서 부족한 것은 이들을 버무리는 능력. 
-> 이를 잘 교육하지도 못하고 있다. -> 이를 다소나마 해소하고자 하는 차원에서 이 교재를 집필하였다. 


여기 인공지능을 연구하고 있는 인문 사회과학 분야에서 인공지능에 대해 연구하고 있는 학자들을 모았다. 동일한 입장을 가지고 있지 않다. 
어떤 학자들은 '빅데이터', '인공지능' 등을 수단으로 삼고 있고, 또 기술에 가까이 있는 연구자들이며, 
어떤 학자들은 인문학적, 철학적 스탠스에서 기술에 대한, 또는 기술과 인간의 관계에 대한 사고를 혁신해야 할 시점에 대해서 이야기한다. 
또 어떤 이들은 인공지능의 사회 시스템에 대한 영향에 대해 고민하고 있다.

이 모든 것들을 보았을 때, 잔여로 남는 것은 기술과 인간의 윤리 간에 통약할 수 없는 것들이다. 이 교재는 이러한 다양한 시각에서 비롯한 통약 불가능한 것들을 무리하게 '해소'하기보다는 독자들 스스로 해결되지 않은 문제들을 바라보기를 기대하고 있다. 







공학자들도, 인공지능을 조금 더 윤리적으로 만들기 위해 나름의 해결책을 제시하기 위해 노력하고 있다. 이들의 목적은 인공지능의 판단 결과를 조금 더 공정하고, 설명가능하고, 프라이버시 보호하는 방향으로 만들기 위해 데이터 수집, 처리 방법, 사후 처리, 알고리즘 설계 등에 개입하는 것. 이러한 작업을 하기 위해서는 위와 같은 개념들은 수학적으로 정의할 수 있어야 한다.
실제로 상당한 성과를 만들어냈으며, XAI는 협업을 더 잘 가능하게 하고, FML은 법적 처방과, 차분 프라이버시는 실제 거대 테크기업들의 

또한, 이러한 해법의 부산물로, 우리는 윤리적 입을 위한 개념들, 특히 윤리성을 의미하는 공정성 등의 용어 안에 얼마나 다층의 개념들이 모호하게 뒤섞여 있었는지를 알게될 것이다...

물론 이러한 방법들이 만병통치약은 아니다. 앞선 챕터들의 논의한 윤리적 문제들과 화합되지 않는 측면들을 살펴보자. 

- 공정거래 - 이렇게 네 가지! (리나 칸, 팀 우 등에 대해서도....)
- XAI
- FML
- Privacy





인공지능, 빅데이터, 기계학습의 관계에 대해서 쓰기...



## 예상 챕터

1부: 인공지능 윤리의 철학적 기초

- 인공지능 윤리의 모색을 위한 철학적, 기술학적 기초 (경북대 김상호)

- 인과성과 책임있는 인공지능 (협의중)

- 인공지능과 정보철학/윤리 (전남대 유용민)

- 포스트휴머니즘과 윤리적 인공지능 (조선대 박선희)

- 자본주의 권력/인공지능 권력 (협의중)



2부: 인공지능 윤리의 적용

- 신뢰할 수 있는/책임있는 인공지능 윤리를 위한 가이드라인 (선문대 박대민)

- 인공지능과 미디어 윤리 (협의중)

- 인공지능과 사회 불평등 (중앙대 이정현)

- 인공지능 시대의 노동 (성균관대 이창준)

- 인공지능 서비스와 저작권 (법무법인 지평 이혜온)

- 인공지능과 리터러시 (협의중)

- 도덕심리와 인공지능 서비스의 개발과 활용 (서강대 사영준)



3부: 인공지능 윤리의 기술적 접근

- 설명가능한 인공지능 (경북대 박찬경)

- 공정한 기계학습 (경북대 박찬경)

- 차분프라이버시를 통한 개인정보 보호 (경북대 박찬경)