# 서문 {.unnumbered}

팬데믹의 공포가 사그라들던 2022년 말, ChatGPT는 바이러스가 등장하던 때와 같이 소리소문 없이 우리 곁에 등장했다. 처음에는 먼 나라 이야기처럼, 기술자들 사이의 재미난 이벤트처럼 여겨지던 OpenAI의 서비스는 어느 순간엔가 우리의 대화를, 노동환경을, 삶을 바꾸어나가기 시작했다. 물론, 이전에도 유사한 기술을 사용하는 서비스는 이미 곳곳에 있었지만, 많은 사람들은 고차원의 대화가 가능한 서비스를 통해, 그 모든 것들이 인공지능과 공존하는 삶으로 나아가는 한걸음, 한걸음이었다는 것을 이제서 깨닫게 된 듯하다.    

인공지능과 함께 살아야 한다는 불편한 사실을 알게된 지금, 우리는 인공지능의 윤리와 관련된 많은 소식들을 언론을 통해 접하게 되었따. 영화에 등장하는 빌런과 꼭 같아 보이는 사업가들과 이들의 폭주에 대한 두려움이 소셜 미디어와 증권 시장을 뒤흔들기도 했고, 안전한 인공지능의 비전에 대한 의견 차이로 보이는 갈등이, 인공지능 산업을 선도하는 기업의 명운을 흔드는 것처럼 보이는 사건도 있었다. 세계적 올드 미디어 기업과 인공지능 산업 진영 간에 창조적 지식에 대한 해석을 둘라싸고, 한 판 법정 싸움도 예고되어 있다. 지난 반세기가 넘도록 세계에서 가장 매력적인 컨텐츠를 만들던 산업의 창작자들은 인공지능의 자동적 정보 생산에 맞서, 창조적 노동의 권리를 지켜내기 위한 대규모 투쟁을 시도하였다. 그 사이 정보 기술에 관한 규제를 선도하고 있는 유럽연합에서는 인공지능법 도입에 거의 합의하였고, 이는 이른바 '브뤼셀 이펙트'를 타고 미국의 IT 산업, 그리고 전세계의 인공지능 생태계의 진화에 큰 영향을 미칠 것이라고 여겨지고 있다.  

이 모든 소동들은 인공지능 윤리에 대한 논의가 변하는 세상을 한탄하는 유희적 담론이 아니라, 우리가 살아내야 하는 산업 생태계의 규칙, 따라서 우리의 일자리, 삶의 가치를 재정의 하는 시급하고도 심대한 영향력을 갖는 문제를 다루고 있다는 것을 보여준다. 그럼에도, 앞서 이야기한 소식들은 여전히 한국에서는 수입된 이야기들처럼 들리는 것도 사실이다. 인공지능을 선도하는 미국 기업들은 새로운 기술과 경쟁자에게 어떻게 대응할지, 이름있는 공학자들과 사업가들이 인공지능의 윤리적 도전에 대해 어떻게 한 마디 보태었는지, 미국 기업의 혁신에 대해 EU는 어떤 규제로 대응하는지에 대한 정보들은 여전히 짧은 단신이나 요약된 비디오를 통해 유통되거나, 아니면 전문가들 사이에 보고서의 형태로만 오고 가는 것이 현실이다. 즉, 어느 때보다 윤리 교육이 필요한 시기에 그에 대한 교육은 공백 상태를 경험하고 있다.

이러한 교육 공백에는 여러 이유가 있겠지만, 무엇보다 인공지능시대의 윤리 문제를 제대로 이해하기 위해서는 폭넓은 학제적 사고가 필요하기 때문이다. 기계와 인간 사이의 새로운 관계정립을 논하고 있는 많은 철학적 발전은 정보과학의 한 분야라고 할 수 있는 '사이버네틱스(cybernetics)' 그리고 인지과학의 성취에 대한 재해석을 바탕으로 한다. 법학자들은 인공지능이 제기하는 창작, 지식, 가치에 대한 다양한 문제들을 법적 언어로 해석하여 규제안으로 만들어내고 있고, 이는 다시 해당 규제에 합치되는 '윤리적 인공지능'의 공학적 개발 노력으로 이어지기도 한다. 이러한 모든 문제들은 심지어 너무나도 빠른 기술변화에 종속되어 있기에, 이를 아우르는 교육 커리큘럼을 만든다는 것은 더욱 더 어렵다.

그러한 어려움에도 불구하고, 이 교재는 시급한 인공지능 윤리 교육의 공백을 메꾸기 위한 시도라고 할 수 있다. 이 교재 집필에 참여한 필진들은 현재 누구보다 기술, 철학, 사회과학의 교차점에서 연구와 교육을 위해 열심히 활동하고 있는 학자들이라고 할 수 있다. 그 중 1부는 인공지능이 만들어내고 있는 철학적 문제들을 기술철학, 인문학 관점에서 일별하고 있다. 또 2부는 그러한 가치의 혼동으로 일어난 사회 변화와 그에 대한 제도적 대응을 다루고 있다. 마지막으로, 3부는 윤리적 문제에 대응하기 위해 공학자들이 다시 고민하여 내어놓은 기술적 솔루션들을 다루고 있다. 

시간적 제약으로 인해, 여전히 다루지 못한 영역들이 많이 있다. 또한 너무나도 빠르게 변하기 때문에, 한 번 교재로 만들어두면 그 지식이 언제까지 유효할지에 대한 두려움이 큰 것도 사실이다. 그 때문에, 우리는 기존 교재 집필에 대한 대안으로 빠르게 업데이트하고, 재공유할 수 있는 온라인 교재의 형태를 택하였다. 이 교재는 오픈소스 소프트웨어를 개발하듯, 공유 플랫폼을 통해 공개되어 있으며, 언제든지 기존 내용의 업데이트, 새로운 저자의 참여가 가능하도록 하였다. 이렇게 재빠른(agile) 지식 공유형태를 취함으로써 우리가 겪고 있는 담론, 지식생산, 교육의 공백을 빠르게 메꿀 수 있게 되기를 희망한다. 

이 교재는 온라인으로 공개되고 있다. 기술만큼이나 철학적, 제도적 논의도 빠르게 변하고 있으며, 이를 업데이트하기에는 온라인 교재가 옳다고 여겼기 때문이다. 이러한 플랫폼을 통해, 빠른 협업을 통한 교재 개발을 위한 협업 모델이 정착되었으면 하는 바람이다. 그리고, 이 교재가 앞으로 출판된다고 하더라도 계속해서 업데이트 될 예정이다.   
알려주세요: 피드백! (사용했을 때, 또 집필을 원할 때)
아직 부족한 부분이 많다. 이 역시 많은 연구자들이 앞으로 도와주길 기대한다. (많은 연구자들이 느끼는 교육에서의 공백을 위해 쓰여지기도 했다.)

이 교재는 RIS 사업의 지원으로 이루어졌다. 지원해주신 RIS 사업단과 경북대학교 미디어공공성센터장 이강형 교수께 감사를 전한다.


2024.1.15.
편자 박찬경




=


그 이유는 너무나도 학제적이기 때문이다. 너무나도 많은 발달이 있었다. 포스트휴먼 이야기는 사이버네틱스가 얽혀오기도 하고, 산업은 경제학이 얽혀온다. 

이 때문에, 해외에서도 아주 잘 짜여진 교과서를 보기는 어려운 것이 현실이다. 

어떻게 할지, EU는 어떻게 할지...학자들은 뭐라고 할지, 선고를 기다리는 사람들처럼 바라보고 있고, 윤리가 우리의 삶에 너무도 가까이 있다느 것을 알면서도, 보고서에서만 만납니다.
기업은 이 문제를 회피할 수 없을 것이며, 사실상 인공지능에 모든 것을 맡길 미래에 인간이 할 것은 윤리적 판단일 뿐이라는 이야기를 합니다.  시

1부는, 2부는... 


에 대한 이해를 

살아가는 산업과 노동, 가치 등, 삶에 대한 이해를 완전히 바꾸어버릴 것이라는 것을 의미한다. 
하지만 어쩐지, 

소문으로 떠돌던 OpenAI의 서비스는 그 때부터 우리의 대화 주제를 완전히 바꾸어버렸습니다. 바이러스를 대체하고 말았지요 (이것의 철학적 의미란...). 아직 우리의 삶을 모조리 바꾸었는지는 모르겠지만, 우리의 언어와 사고방식은 분명 바뀌었습니다. 학생들은 번역기를 이용한 티가 팍팍 나는 레포트를 써 내고 있습니다. 또 그 이전에도 있었던 추천 알고리즘을 인공지능이라고 부르기 시작했습니다. 어찌 보면, 이미 우리 주변에 와 있던 인공지능을 이제야 알아보고 화들짝 놀란 것 같기도 합니다.   





문제는 그보다도 근본적인 것으로 보입니다. 우리의 삶을 떠나, 인공지능의 삶에 대한 이야기까지 이루어지고 있습니다.

우리는 이러한 변화에 대해 얼마나 준비하고 있을까요?
사실 인공지능이 모든 것을 해 준다면, 우리에게 필요한 것은 인공지능을 설계하고 조작하는 능력 만큼이나, 인공지능과 어떻게 함께 살아가야 할 것인가에 대한 준비가 아닐까요. 

이 책은 그러한 관점에서 윤리에 대해 이야기 하고자 합니다. 윤리는 함께 살아가는 것에 대한 이야기 입니다.




정책 보고서들과 해외의 뉴스들이 오가고 있다. 

급변하는,,,Open AI 

뉴욕 타임즈 v. Open AI
미국의 헐리우드 파업에서 AI의 역할...

그런데, EU의 것들만 봐도, 어마어마한 정치적 논란 속에서... 그리고 서류들이 오가고 있는 상황 속에서....

https://www.europarl.europa.eu/doceo/document/TA-9-2023-0236_EN.html

Demystifying the Draft EU Artificial Intelligence Act
Analysing the good, the bad, and the unclear elements of the proposed approach


또, ACM Fair ML 등에서는 철학자들과 공학자들 간의 철학적 논의가 오가고 있다. 


우리의 이야기는 너무도 피상적, 기술적.
-> 우리 교육에서 부족한 것은 이들을 버무리는 능력. 
-> 이를 잘 교육하지도 못하고 있다. -> 이를 다소나마 해소하고자 하는 차원에서 이 교재를 집필하였다. 


여기 인공지능을 연구하고 있는 인문 사회과학 분야에서 인공지능에 대해 연구하고 있는 학자들을 모았다. 동일한 입장을 가지고 있지 않다. 
어떤 학자들은 '빅데이터', '인공지능' 등을 수단으로 삼고 있고, 또 기술에 가까이 있는 연구자들이며, 
어떤 학자들은 인문학적, 철학적 스탠스에서 기술에 대한, 또는 기술과 인간의 관계에 대한 사고를 혁신해야 할 시점에 대해서 이야기한다. 
또 어떤 이들은 인공지능의 사회 시스템에 대한 영향에 대해 고민하고 있다.

이 모든 것들을 보았을 때, 잔여로 남는 것은 기술과 인간의 윤리 간에 통약할 수 없는 것들이다. 이 교재는 이러한 다양한 시각에서 비롯한 통약 불가능한 것들을 무리하게 '해소'하기보다는 독자들 스스로 해결되지 않은 문제들을 바라보기를 기대하고 있다. 







공학자들도, 인공지능을 조금 더 윤리적으로 만들기 위해 나름의 해결책을 제시하기 위해 노력하고 있다. 이들의 목적은 인공지능의 판단 결과를 조금 더 공정하고, 설명가능하고, 프라이버시 보호하는 방향으로 만들기 위해 데이터 수집, 처리 방법, 사후 처리, 알고리즘 설계 등에 개입하는 것. 이러한 작업을 하기 위해서는 위와 같은 개념들은 수학적으로 정의할 수 있어야 한다.
실제로 상당한 성과를 만들어냈으며, XAI는 협업을 더 잘 가능하게 하고, FML은 법적 처방과, 차분 프라이버시는 실제 거대 테크기업들의 

또한, 이러한 해법의 부산물로, 우리는 윤리적 입을 위한 개념들, 특히 윤리성을 의미하는 공정성 등의 용어 안에 얼마나 다층의 개념들이 모호하게 뒤섞여 있었는지를 알게될 것이다...

물론 이러한 방법들이 만병통치약은 아니다. 앞선 챕터들의 논의한 윤리적 문제들과 화합되지 않는 측면들을 살펴보자. 

- 공정거래 - 이렇게 네 가지! (리나 칸, 팀 우 등에 대해서도....)
- XAI
- FML
- Privacy





인공지능, 빅데이터, 기계학습의 관계에 대해서 쓰기...



## 예상 챕터

1부: 인공지능 윤리의 철학적 기초

- 인공지능 윤리의 모색을 위한 철학적, 기술학적 기초 (경북대 김상호)

- 인과성과 책임있는 인공지능 (협의중)

- 인공지능과 정보철학/윤리 (전남대 유용민)

- 포스트휴머니즘과 윤리적 인공지능 (조선대 박선희)

- 자본주의 권력/인공지능 권력 (협의중)



2부: 인공지능 윤리의 적용

- 신뢰할 수 있는/책임있는 인공지능 윤리를 위한 가이드라인 (선문대 박대민)

- 인공지능과 미디어 윤리 (협의중)

- 인공지능과 사회 불평등 (중앙대 이정현)

- 인공지능 시대의 노동 (성균관대 이창준)

- 인공지능 서비스와 저작권 (법무법인 지평 이혜온)

- 인공지능과 리터러시 (협의중)

- 도덕심리와 인공지능 서비스의 개발과 활용 (서강대 사영준)



3부: 인공지능 윤리의 기술적 접근

- 설명가능한 인공지능 (경북대 박찬경)

- 공정한 기계학습 (경북대 박찬경)

- 차분프라이버시를 통한 개인정보 보호 (경북대 박찬경)


