# 인공지능과 정보철학/윤리

*유용민 (전담대학교 미디어커뮤니케이션학과)*

## 서론

1990년대 후반 인터넷과 컴퓨터 혁명의 진전으로 우리 한국사회에서 정보사회(information society)라는 개념이 도입된지도 적지 않은 시간이 지났다. 새로운 기술이 도입될 때마다 그 기술을 어떻게 이해해야 할지? 그리고 그러한 이해를 바탕으로 해당 기술을 어떻게 활용해야 할지에 관한 철학적, 윤리적 논쟁은 늘 반복되어 왔다. 마찬가지로 인터넷 윤리, 컴퓨터 윤리, 사이버 윤리, 데이터 윤리 같은 용어들 옆에 놓고 보면, 정보철학이나 정보윤리라는 말은 크게 새롭게 와닿지 않을 수 있다. 일반인들이나 전문가들도 이런 용어들을 쭉 펼쳐 놓고 보면 과연 이 용어들의 의미를 어떻게 구별해야 할지? 즉 정보윤리란 무엇인가?에 대해 명확한 답을 얻기 어렵다. 비슷비슷해 보이고, 별 차이 없는 이야기를 하자는 것 아닌가 하는 결론에 도달하기 쉽기 때문이다. 정보든 데이터든, 정보통신기술이든 최근에 새롭게 부상한 지능정보기술이든 윤리적으로 바람직하게 활용하자는 주장으로 들리기 때문이다.

이런 현실의 바탕에는 정보를 협소하게 이해하는 현대 지식이 배경에 놓여 있다. 예를 들어 정보를 잘 활용하는 것의 중요성과 가치를 설파하는 기존의 광범위한 정보윤리 논의들은 대부분 정보를 정보통신기술(ICT) 발달을 통해서 정보에 대한 의존이 절대적으로 커진 현대사회의 윤리학의 한 응용(applied) 영역으로 간주하는 경향이 있다. 물리적 실체가 없이 정보통신기술을 기반으로 정보의 생산, 유통, 소비 과정에서 발생하는 권리와 책임, 사회적 해악, 긴장 갈등 같은 실천적인 문제들을 윤리적으로 풀어야 한다는 도덕적 사고 체계가 이러한 정보윤리론의 골자이자 거의 전부였다. 이러한 자기충족적인 정보윤리론의 철학적 근저에는 정보적 주체(정보를 활용하는 인간)와 정보적 대상(혹은 존재) 사이의 이원론이 자리잡고 있다. 이러한 이원론적 사고 안에서는 정보든, 미디어든, 데이터든 그 대상(target)이 바뀌는 것이 별다른 의미가 없다. 어차피 그것들을 사용하는 인간 주체의 자기 이해가 달라지지 않고, 따라서 윤리적 주체로서의 사람과 기술적인 대상들 사이의 관계도 달라지지 않으며, 결과적으로 인간에게 정보가 갖는 의미 또한 변화가 없게 된다. 그 대상의 이름이 정보든, 데이터든, 알고리즘이든 인공지능이든, 또는 초거대 인공지능이든, 그저 ‘잘 쓰면 그만인 것을’이라는 말이다.

하지만 최근 인공지능 기술의 눈부신 발전 상에서 목격되고 있듯, 기술의 본질적인 특성이나 형식이 달라질 경우에도 그럴 수 있을까를 질문해 본다면, 답은 간단치 않다. 기술의 특성 변화로 인하여 인간과 기술이 관계맺는 양상이 달라진다면, 기술과 인간의 상호작용 과정과 그 결과가 갖는 의미도 달라지기 때문이다. 예컨대, 기존의 미디어는 인간의 직간접적 통제에 의해 주입된 정보(input data/information)를 송신자의 의도나 목적에 따라 정해진 흐름에 전달(transmit)하고, 이용자는 이를 수신받아 활용하는 도구라는 범주적 특성 하에 인간과 관계를 맺었다. 그러나 근래 등장한 챗GPT 같은 생성형 인공지능 기술은 물론이거니와 심지어 단순한 알고리즘조차 인간으로부터 위임을 받아 스스로 행위함으로써, 과거의 기술과는 전혀 다른 존재의 가능성을 보여주고 있다. 이런 변화의 양상을 고려하면, 정보를 이해하는 방식과 그러한 이해를 정보 현상에 적용하는 과정은 과거와 같은 방식으로 접근해서는 곤란한 측면이 있다. 인공지능 기반 미디어 서비스가 보급되면서 인공지능을 법적 또는 윤리적인 행위 주체로 볼 것이냐 아니냐 같은 논쟁이 제기되는 이유도 바로 이런 맥락 때문이다.

인공지능 시대를 맞이하여 이런 맥락은 더욱 더 전면화되고 보편화될 것이란 전망이 있다. 정보윤리도 정보를 활용하는 인간윤리 혹은 정보 생산, 유통, 소비 과정에서 발생하는 도덕적 해악이나 피해의 문제를 다루는 인간윤리 또는 사회윤리라는 기존의 관점으로 설명하기 어려운 문제들이 속속들이 등장하고 있기 때문이다. 그래서 정보 현상 혹은 정보 개념을 이해하는 방식을 근본적인 수준에서, 즉 철학적으로 재구성하고, 그러한 철학적 원리 하에서 정보와 관련한 복잡다양한 현실적 문제들에 대처해 가야 한다는 문제의식들이 최근 서구 학계로부터 제기된 바 있다. 정보철학(information philosophy: PI) 분야가 대표적이다. 여기서 말하는 정보철학이란 정보를 세계를 이해하는 근본 개념으로 상정하고, 정보에 관한 철학적 원리와 이론을 개발하려는 철학적 논의 분야를 지칭한다. 이 용어를 공식적으로 창안하여 널리 보급한 학자는 이탈리아 출신으로 옥스퍼드대학에서 인터넷, 정보 윤리에 관한 학술적 작업을 주도하고 있는 정보철학자 루치아노 플로리디(Luciano Floridi)다. 플로리디에 따르면 정보철학은 사물의 제1원인과 제1원리를 취급하는 철학(Philosophia Prima)이다.[^info-1] 즉 정보 또는 정보를 통해 구성되는 세계 자체를 이해하는 것이 목표인 셈이다. 이러한 정보철학은 근본적으로 정보가 어떤 역할을 수행하며, 점점 더 확장되고 있는 정보의 중요성을 어떻게 이해할 수 있을지에 관한 원리와 토대를 찾는데 도움이 될 수 있다. 쉽게 말하면, 과거의 ‘계급이론’이 계급이라는 렌즈로 세계와 역사를 이해하고자 했던 것처럼, 정보라는 차원을 통해서 사회와 세계를 이해해 보려는 철학 분야로 이해할 수 있다.

[^info-1]: 정보철학의 기원은 거슬러 올라가면 1940년대 후반 노르베르트 위너가 개념적 틀을 정초한 사이버네틱스(cybernetics) 이론에서 찾아볼 수 있다. 사이버네틱스 이론은 신호와 신호가 어떻게 관련을 맺는지를 설명하는 수학적 이론으로 제안되었지만, 1990년대 중후반 정보통신기술의 발달로 인해 등장한 정보화 물결과 맞물려 정보이론의 발전에 중요한 영향력을 행사했다.

이 장에서는 루치아노 플로리디의 정보철학을 토대로 인공지능과 알고리즘 같은 최근의 기술적인 대상들과 인간이 관계를 맺어가는 현대사회에서 정보를 둘러싼 문제를 어떻게 이해해야 할지에 관한 논의를 제공하고, 나아가 인공지능 시대에 정보철학적 접근에 주목해야 할 이유에 대해서도 살펴보고자 한다. 이러한 논의를 통해 이 장은 인공지능 같은 비인간 존재들과 인간이 대등한 관계를 복잡다양하게 맺어가는 오늘날 기존의 미시윤리학적이고 인간윤리학적인 접근이 가진 한계를 비판적으로 진단하면서, 정보에 대한 조금 더 보편적인 사고가 필요하다는 문제의식을 공유하고자 한다.
